In [1]:
import json
from generate_brats_3d_vqa_dataset_from_openai import validate_vqa_lists

In [2]:
train_results = "brats_gli_3d_vqa_subjTrue_train_updated_v1_seed0_new.json"
val_results = "brats_gli_3d_vqa_subjTrue_val_updated_v1_seed0_new.json"
test_results = "brats_gli_3d_vqa_subjTrue_test_updated_v1_seed0_new.json"

In [3]:
with open(train_results, 'r') as f:
    train_vqa_data = json.load(f)
with open(val_results, 'r') as f:
    val_vqa_data = json.load(f)
with open(test_results, 'r') as f:
    test_vqa_data = json.load(f)

In [4]:
results1, results2, results3 = validate_vqa_lists(train_vqa_data), validate_vqa_lists(val_vqa_data), validate_vqa_lists(test_vqa_data)

Loaded 20,736 rows  (20,736)

▶ Combo distribution (overall)
       combo  n_questions
      (1, 2)         1031
   (1, 2, 3)         1386
(1, 2, 3, 4)         1732
   (1, 2, 4)         1560
      (1, 3)         1292
   (1, 3, 4)         1640
      (1, 4)         1525
        (1,)          679
      (2, 3)         1406
   (2, 3, 4)         1715
      (2, 4)         1614
        (2,)          856
      (3, 4)         1658
        (3,)         1134
        (4,)         1508

▶ Unique Q/A counts (overall)
   • questions : 20,173
   • answers   : 19,440
Loaded 2,784 rows  (2,784)

▶ Combo distribution (overall)
       combo  n_questions
      (1, 2)          139
   (1, 2, 3)          201
(1, 2, 3, 4)          184
   (1, 2, 4)          209
      (1, 3)          174
   (1, 3, 4)          234
      (1, 4)          204
        (1,)           88
      (2, 3)          207
   (2, 3, 4)          235
      (2, 4)          211
        (2,)          117
      (3, 4)          211
        (3,)          163
        (4,)          207

▶ Unique Q/A counts (overall)
   • questions : 2,769
   • answers   : 2,686
Loaded 2,416 rows  (2,416)

▶ Combo distribution (overall)
    combo  n_questions
   (1, 2)          140
(1, 2, 3)          189
(1, 2, 4)          200
   (1, 3)          163
(1, 3, 4)          221
   (1, 4)          199
     (1,)           85
   (2, 3)          197
(2, 3, 4)          116
   (2, 4)          201
     (2,)          124
   (3, 4)          211
     (3,)          160
     (4,)          210

▶ Unique Q/A counts (overall)
   • questions : 2,400
   • answers   : 2,304

In [5]:
for k, v in results1.items():
    display(k)
    display(v)

'combo_overall'

           combo  n_questions
12        (1, 2)         1031
9      (1, 2, 3)         1386
0   (1, 2, 3, 4)         1732
5      (1, 2, 4)         1560
10        (1, 3)         1292
3      (1, 3, 4)         1640
6         (1, 4)         1525
14          (1,)          679
8         (2, 3)         1406
1      (2, 3, 4)         1715
4         (2, 4)         1614
13          (2,)          856
2         (3, 4)         1658
11          (3,)         1134
7           (4,)         1508

'combo_per_label'

                                        label_name         combo  n_questions
0                                 Enhancing Tissue          (1,)          185
1                                 Enhancing Tissue        (1, 2)          233
2                                 Enhancing Tissue     (1, 2, 3)          333
3                                 Enhancing Tissue  (1, 2, 3, 4)          435
4                                 Enhancing Tissue     (1, 2, 4)          397
5                                 Enhancing Tissue        (1, 3)          311
6                                 Enhancing Tissue     (1, 3, 4)          393
7                                 Enhancing Tissue        (1, 4)          383
8                                 Enhancing Tissue          (2,)          204
9                                 Enhancing Tissue        (2, 3)          353
10                                Enhancing Tissue     (2, 3, 4)          465
11                                Enhancing Tissue        (2, 4)          406
12                                Enhancing Tissue          (3,)          292
13                                Enhancing Tissue        (3, 4)          403
14                                Enhancing Tissue          (4,)          391
15                             Non-Enhancing Tumor          (1,)          187
16                             Non-Enhancing Tumor        (1, 2)          266
17                             Non-Enhancing Tumor     (1, 2, 3)          340
18                             Non-Enhancing Tumor  (1, 2, 3, 4)          433
19                             Non-Enhancing Tumor     (1, 2, 4)          396
20                             Non-Enhancing Tumor        (1, 3)          320
21                             Non-Enhancing Tumor     (1, 3, 4)          407
22                             Non-Enhancing Tumor        (1, 4)          388
23                             Non-Enhancing Tumor          (2,)          211
24                             Non-Enhancing Tumor        (2, 3)          352
25                             Non-Enhancing Tumor     (2, 3, 4)          405
26                             Non-Enhancing Tumor        (2, 4)          390
27                             Non-Enhancing Tumor          (3,)          277
28                             Non-Enhancing Tumor        (3, 4)          434
29                             Non-Enhancing Tumor          (4,)          378
30                                Resection Cavity          (1,)          145
31                                Resection Cavity        (1, 2)          262
32                                Resection Cavity     (1, 2, 3)          363
33                                Resection Cavity  (1, 2, 3, 4)          422
34                                Resection Cavity     (1, 2, 4)          391
35                                Resection Cavity        (1, 3)          326
36                                Resection Cavity     (1, 3, 4)          429
37                                Resection Cavity        (1, 4)          377
38                                Resection Cavity          (2,)          218
39                                Resection Cavity        (2, 3)          355
40                                Resection Cavity     (2, 3, 4)          421
41                                Resection Cavity        (2, 4)          398
42                                Resection Cavity          (3,)          293
43                                Resection Cavity        (3, 4)          414
44                                Resection Cavity          (4,)          370
45  Surrounding Non-enhancing FLAIR hyperintensity          (1,)          162
46  Surrounding Non-enhancing FLAIR hyperintensity        (1, 2)          270
47  Surrounding Non-enhancing FLAIR hyperintensity     (1, 2, 3)          350
48  Surrounding Non-enhancing FLAIR hyperintensity  (1, 2, 3, 4)          442
49  Surrounding Non-enhancing FLAIR hyperintensity     (1, 2, 4)          376
50  Surrounding Non-enhancing FLAIR hyperintensity        (1, 3)          335
51  Surrounding Non-enhancing FLAIR hyperintensity     (1, 3, 4)          411
52  Surrounding Non-enhancing FLAIR hyperintensity        (1, 4)          377
53  Surrounding Non-enhancing FLAIR hyperintensity          (2,)          223
54  Surrounding Non-enhancing FLAIR hyperintensity        (2, 3)          346
55  Surrounding Non-enhancing FLAIR hyperintensity     (2, 3, 4)          424
56  Surrounding Non-enhancing FLAIR hyperintensity        (2, 4)          420
57  Surrounding Non-enhancing FLAIR hyperintensity          (3,)          272
58  Surrounding Non-enhancing FLAIR hyperintensity        (3, 4)          407
59  Surrounding Non-enhancing FLAIR hyperintensity          (4,)          369

'combo_per_label_type'

,label_name,type,combo,n_questions
0,Enhancing Tissue,area,"(1,)",185
1,Enhancing Tissue,area,"(1, 2)",142
2,Enhancing Tissue,area,"(1, 2, 3)",163
3,Enhancing Tissue,area,"(1, 2, 3, 4)",142
4,Enhancing Tissue,area,"(1, 2, 4)",170
...,...,...,...,...
123,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(1, 3, 4)",138
124,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(2, 3)",125
125,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(2, 3, 4)",121
126,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3,)",272
127,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3, 4)",287

'unique_q_per_label'

                                       label_name  n_unique_questions
0                                Enhancing Tissue                5050
1                             Non-Enhancing Tumor                5039
2                                Resection Cavity                5056
3  Surrounding Non-enhancing FLAIR hyperintensity                5028

'unique_a_per_label'

                                       label_name  n_unique_answers
0                                Enhancing Tissue              4870
1                             Non-Enhancing Tumor              4809
2                                Resection Cavity              4880
3  Surrounding Non-enhancing FLAIR hyperintensity              4881

'unique_q_per_label_type'

,label_name,type,n_unique_questions
0,Enhancing Tissue,area,1278
1,Enhancing Tissue,region,1286
2,Enhancing Tissue,satellite,1249
3,Enhancing Tissue,shape,1256
4,Non-Enhancing Tumor,area,1274
5,Non-Enhancing Tumor,region,1285
6,Non-Enhancing Tumor,satellite,1245
7,Non-Enhancing Tumor,shape,1254
8,Resection Cavity,area,1285
9,Resection Cavity,region,1279
10,Resection Cavity,satellite,1255
11,Resection Cavity,shape,1258
12,Surrounding Non-enhancing FLAIR hyperintensity,area,1277
13,Surrounding Non-enhancing FLAIR hyperintensity,region,1283
14,Surrounding Non-enhancing FLAIR hyperintensity,satellite,1244
15,Surrounding Non-enhancing FLAIR hyperintensity,shape,1251

'unique_a_per_label_type'

,label_name,type,n_unique_answers
0,Enhancing Tissue,area,1283
1,Enhancing Tissue,region,1276
2,Enhancing Tissue,satellite,1246
3,Enhancing Tissue,shape,1078
4,Non-Enhancing Tumor,area,1277
5,Non-Enhancing Tumor,region,1235
6,Non-Enhancing Tumor,satellite,1225
7,Non-Enhancing Tumor,shape,1100
8,Resection Cavity,area,1276
9,Resection Cavity,region,1282
10,Resection Cavity,satellite,1240
11,Resection Cavity,shape,1099
12,Surrounding Non-enhancing FLAIR hyperintensity,area,1274
13,Surrounding Non-enhancing FLAIR hyperintensity,region,1296
14,Surrounding Non-enhancing FLAIR hyperintensity,satellite,1218
15,Surrounding Non-enhancing FLAIR hyperintensity,shape,1103

In [6]:
for k, v in results2.items():
    display(k)
    display(v)

'combo_overall'

           combo  n_questions
12        (1, 2)          139
8      (1, 2, 3)          201
9   (1, 2, 3, 4)          184
4      (1, 2, 4)          209
10        (1, 3)          174
1      (1, 3, 4)          234
7         (1, 4)          204
14          (1,)           88
6         (2, 3)          207
0      (2, 3, 4)          235
3         (2, 4)          211
13          (2,)          117
2         (3, 4)          211
11          (3,)          163
5           (4,)          207

'combo_per_label'

                                        label_name         combo  n_questions
0                                 Enhancing Tissue          (1,)           22
1                                 Enhancing Tissue        (1, 2)           25
2                                 Enhancing Tissue     (1, 2, 3)           49
3                                 Enhancing Tissue  (1, 2, 3, 4)           44
4                                 Enhancing Tissue     (1, 2, 4)           49
5                                 Enhancing Tissue        (1, 3)           38
6                                 Enhancing Tissue     (1, 3, 4)           51
7                                 Enhancing Tissue        (1, 4)           57
8                                 Enhancing Tissue          (2,)           30
9                                 Enhancing Tissue        (2, 3)           52
10                                Enhancing Tissue     (2, 3, 4)           63
11                                Enhancing Tissue        (2, 4)           58
12                                Enhancing Tissue          (3,)           48
13                                Enhancing Tissue        (3, 4)           56
14                                Enhancing Tissue          (4,)           54
15                             Non-Enhancing Tumor          (1,)           27
16                             Non-Enhancing Tumor        (1, 2)           36
17                             Non-Enhancing Tumor     (1, 2, 3)           48
18                             Non-Enhancing Tumor  (1, 2, 3, 4)           45
19                             Non-Enhancing Tumor     (1, 2, 4)           47
20                             Non-Enhancing Tumor        (1, 3)           43
21                             Non-Enhancing Tumor     (1, 3, 4)           60
22                             Non-Enhancing Tumor        (1, 4)           47
23                             Non-Enhancing Tumor          (2,)           31
24                             Non-Enhancing Tumor        (2, 3)           52
25                             Non-Enhancing Tumor     (2, 3, 4)           59
26                             Non-Enhancing Tumor        (2, 4)           54
27                             Non-Enhancing Tumor          (3,)           39
28                             Non-Enhancing Tumor        (3, 4)           58
29                             Non-Enhancing Tumor          (4,)           50
30                                Resection Cavity          (1,)           14
31                                Resection Cavity        (1, 2)           41
32                                Resection Cavity     (1, 2, 3)           48
33                                Resection Cavity  (1, 2, 3, 4)           45
34                                Resection Cavity     (1, 2, 4)           57
35                                Resection Cavity        (1, 3)           44
36                                Resection Cavity     (1, 3, 4)           71
37                                Resection Cavity        (1, 4)           44
38                                Resection Cavity          (2,)           26
39                                Resection Cavity        (2, 3)           57
40                                Resection Cavity     (2, 3, 4)           60
41                                Resection Cavity        (2, 4)           44
42                                Resection Cavity          (3,)           38
43                                Resection Cavity        (3, 4)           54
44                                Resection Cavity          (4,)           53
45  Surrounding Non-enhancing FLAIR hyperintensity          (1,)           25
46  Surrounding Non-enhancing FLAIR hyperintensity        (1, 2)           37
47  Surrounding Non-enhancing FLAIR hyperintensity     (1, 2, 3)           56
48  Surrounding Non-enhancing FLAIR hyperintensity  (1, 2, 3, 4)           50
49  Surrounding Non-enhancing FLAIR hyperintensity     (1, 2, 4)           56
50  Surrounding Non-enhancing FLAIR hyperintensity        (1, 3)           49
51  Surrounding Non-enhancing FLAIR hyperintensity     (1, 3, 4)           52
52  Surrounding Non-enhancing FLAIR hyperintensity        (1, 4)           56
53  Surrounding Non-enhancing FLAIR hyperintensity          (2,)           30
54  Surrounding Non-enhancing FLAIR hyperintensity        (2, 3)           46
55  Surrounding Non-enhancing FLAIR hyperintensity     (2, 3, 4)           53
56  Surrounding Non-enhancing FLAIR hyperintensity        (2, 4)           55
57  Surrounding Non-enhancing FLAIR hyperintensity          (3,)           38
58  Surrounding Non-enhancing FLAIR hyperintensity        (3, 4)           43
59  Surrounding Non-enhancing FLAIR hyperintensity          (4,)           50

'combo_per_label_type'

,label_name,type,combo,n_questions
0,Enhancing Tissue,area,"(1,)",22
1,Enhancing Tissue,area,"(1, 2)",15
2,Enhancing Tissue,area,"(1, 2, 3)",23
3,Enhancing Tissue,area,"(1, 2, 3, 4)",20
4,Enhancing Tissue,area,"(1, 2, 4)",22
...,...,...,...,...
123,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(1, 3, 4)",18
124,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(2, 3)",17
125,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(2, 3, 4)",16
126,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3,)",38
127,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3, 4)",29

'unique_q_per_label'

                                       label_name  n_unique_questions
0                                Enhancing Tissue                 693
1                             Non-Enhancing Tumor                 692
2                                Resection Cavity                 694
3  Surrounding Non-enhancing FLAIR hyperintensity                 690

'unique_a_per_label'

                                       label_name  n_unique_answers
0                                Enhancing Tissue               667
1                             Non-Enhancing Tumor               671
2                                Resection Cavity               675
3  Surrounding Non-enhancing FLAIR hyperintensity               673

'unique_q_per_label_type'

,label_name,type,n_unique_questions
0,Enhancing Tissue,area,174
1,Enhancing Tissue,region,174
2,Enhancing Tissue,satellite,171
3,Enhancing Tissue,shape,174
4,Non-Enhancing Tumor,area,174
5,Non-Enhancing Tumor,region,173
6,Non-Enhancing Tumor,satellite,172
7,Non-Enhancing Tumor,shape,173
8,Resection Cavity,area,174
9,Resection Cavity,region,174
10,Resection Cavity,satellite,173
11,Resection Cavity,shape,174
12,Surrounding Non-enhancing FLAIR hyperintensity,area,174
13,Surrounding Non-enhancing FLAIR hyperintensity,region,173
14,Surrounding Non-enhancing FLAIR hyperintensity,satellite,172
15,Surrounding Non-enhancing FLAIR hyperintensity,shape,173

'unique_a_per_label_type'

,label_name,type,n_unique_answers
0,Enhancing Tissue,area,174
1,Enhancing Tissue,region,174
2,Enhancing Tissue,satellite,173
3,Enhancing Tissue,shape,148
4,Non-Enhancing Tumor,area,172
5,Non-Enhancing Tumor,region,171
6,Non-Enhancing Tumor,satellite,173
7,Non-Enhancing Tumor,shape,155
8,Resection Cavity,area,173
9,Resection Cavity,region,172
10,Resection Cavity,satellite,173
11,Resection Cavity,shape,157
12,Surrounding Non-enhancing FLAIR hyperintensity,area,174
13,Surrounding Non-enhancing FLAIR hyperintensity,region,174
14,Surrounding Non-enhancing FLAIR hyperintensity,satellite,173
15,Surrounding Non-enhancing FLAIR hyperintensity,shape,152

In [7]:
for k, v in results3.items():
    display(k)
    display(v)

'combo_overall'

        combo  n_questions
10     (1, 2)          140
7   (1, 2, 3)          189
4   (1, 2, 4)          200
8      (1, 3)          163
0   (1, 3, 4)          221
5      (1, 4)          199
13       (1,)           85
6      (2, 3)          197
12  (2, 3, 4)          116
3      (2, 4)          201
11       (2,)          124
1      (3, 4)          211
9        (3,)          160
2        (4,)          210

'combo_per_label'

                                        label_name      combo  n_questions
0                                 Enhancing Tissue       (1,)           22
1                                 Enhancing Tissue     (1, 2)           23
2                                 Enhancing Tissue  (1, 2, 3)           48
3                                 Enhancing Tissue  (1, 2, 4)           52
4                                 Enhancing Tissue     (1, 3)           40
5                                 Enhancing Tissue  (1, 3, 4)           46
6                                 Enhancing Tissue     (1, 4)           54
7                                 Enhancing Tissue       (2,)           33
8                                 Enhancing Tissue     (2, 3)           49
9                                 Enhancing Tissue  (2, 3, 4)           31
10                                Enhancing Tissue     (2, 4)           53
11                                Enhancing Tissue       (3,)           46
12                                Enhancing Tissue     (3, 4)           50
13                                Enhancing Tissue       (4,)           57
14                             Non-Enhancing Tumor       (1,)           21
15                             Non-Enhancing Tumor     (1, 2)           36
16                             Non-Enhancing Tumor  (1, 2, 3)           43
17                             Non-Enhancing Tumor  (1, 2, 4)           46
18                             Non-Enhancing Tumor     (1, 3)           39
19                             Non-Enhancing Tumor  (1, 3, 4)           58
20                             Non-Enhancing Tumor     (1, 4)           53
21                             Non-Enhancing Tumor       (2,)           32
22                             Non-Enhancing Tumor     (2, 3)           51
23                             Non-Enhancing Tumor  (2, 3, 4)           28
24                             Non-Enhancing Tumor     (2, 4)           51
25                             Non-Enhancing Tumor       (3,)           38
26                             Non-Enhancing Tumor     (3, 4)           58
27                             Non-Enhancing Tumor       (4,)           50
28                                Resection Cavity       (1,)           17
29                                Resection Cavity     (1, 2)           42
30                                Resection Cavity  (1, 2, 3)           44
31                                Resection Cavity  (1, 2, 4)           52
32                                Resection Cavity     (1, 3)           39
33                                Resection Cavity  (1, 3, 4)           67
34                                Resection Cavity     (1, 4)           43
35                                Resection Cavity       (2,)           29
36                                Resection Cavity     (2, 3)           54
37                                Resection Cavity  (2, 3, 4)           24
38                                Resection Cavity     (2, 4)           47
39                                Resection Cavity       (3,)           40
40                                Resection Cavity     (3, 4)           53
41                                Resection Cavity       (4,)           53
42  Surrounding Non-enhancing FLAIR hyperintensity       (1,)           25
43  Surrounding Non-enhancing FLAIR hyperintensity     (1, 2)           39
44  Surrounding Non-enhancing FLAIR hyperintensity  (1, 2, 3)           54
45  Surrounding Non-enhancing FLAIR hyperintensity  (1, 2, 4)           50
46  Surrounding Non-enhancing FLAIR hyperintensity     (1, 3)           45
47  Surrounding Non-enhancing FLAIR hyperintensity  (1, 3, 4)           50
48  Surrounding Non-enhancing FLAIR hyperintensity     (1, 4)           49
49  Surrounding Non-enhancing FLAIR hyperintensity       (2,)           30
50  Surrounding Non-enhancing FLAIR hyperintensity     (2, 3)           43
51  Surrounding Non-enhancing FLAIR hyperintensity  (2, 3, 4)           33
52  Surrounding Non-enhancing FLAIR hyperintensity     (2, 4)           50
53  Surrounding Non-enhancing FLAIR hyperintensity       (3,)           36
54  Surrounding Non-enhancing FLAIR hyperintensity     (3, 4)           50
55  Surrounding Non-enhancing FLAIR hyperintensity       (4,)           50

'combo_per_label_type'

,label_name,type,combo,n_questions
0,Enhancing Tissue,area,"(1,)",22
1,Enhancing Tissue,area,"(1, 2)",18
2,Enhancing Tissue,area,"(1, 2, 3)",23
3,Enhancing Tissue,area,"(1, 2, 4)",23
4,Enhancing Tissue,area,"(1, 3)",22
...,...,...,...,...
107,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(1, 3, 4)",19
108,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(2, 3)",17
109,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(2, 3, 4)",9
110,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3,)",36
111,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3, 4)",32

'unique_q_per_label'

                                       label_name  n_unique_questions
0                                Enhancing Tissue                 601
1                             Non-Enhancing Tumor                 600
2                                Resection Cavity                 598
3  Surrounding Non-enhancing FLAIR hyperintensity                 601

'unique_a_per_label'

                                       label_name  n_unique_answers
0                                Enhancing Tissue               578
1                             Non-Enhancing Tumor               572
2                                Resection Cavity               579
3  Surrounding Non-enhancing FLAIR hyperintensity               575

'unique_q_per_label_type'

,label_name,type,n_unique_questions
0,Enhancing Tissue,area,150
1,Enhancing Tissue,region,151
2,Enhancing Tissue,satellite,151
3,Enhancing Tissue,shape,149
4,Non-Enhancing Tumor,area,150
5,Non-Enhancing Tumor,region,151
6,Non-Enhancing Tumor,satellite,149
7,Non-Enhancing Tumor,shape,150
8,Resection Cavity,area,151
9,Resection Cavity,region,151
10,Resection Cavity,satellite,149
11,Resection Cavity,shape,147
12,Surrounding Non-enhancing FLAIR hyperintensity,area,151
13,Surrounding Non-enhancing FLAIR hyperintensity,region,151
14,Surrounding Non-enhancing FLAIR hyperintensity,satellite,151
15,Surrounding Non-enhancing FLAIR hyperintensity,shape,148

'unique_a_per_label_type'

,label_name,type,n_unique_answers
0,Enhancing Tissue,area,151
1,Enhancing Tissue,region,151
2,Enhancing Tissue,satellite,148
3,Enhancing Tissue,shape,130
4,Non-Enhancing Tumor,area,151
5,Non-Enhancing Tumor,region,146
6,Non-Enhancing Tumor,satellite,151
7,Non-Enhancing Tumor,shape,126
8,Resection Cavity,area,151
9,Resection Cavity,region,151
10,Resection Cavity,satellite,148
11,Resection Cavity,shape,129
12,Surrounding Non-enhancing FLAIR hyperintensity,area,150
13,Surrounding Non-enhancing FLAIR hyperintensity,region,151
14,Surrounding Non-enhancing FLAIR hyperintensity,satellite,146
15,Surrounding Non-enhancing FLAIR hyperintensity,shape,129