In [1]:
import json
from create_brats_3d_vqa_dataset_from_openai import validate_vqa_lists

In [2]:
#train_results = "brats_gli_3d_vqa_subjTrue_train_updated_v1_seed0_new.json"
#val_results = "brats_gli_3d_vqa_subjTrue_val_updated_v1_seed0_new.json"
#test_results = "brats_gli_3d_vqa_subjTrue_test_updated_v1_seed0_new.json"
train_results = "brats_gli_3d_vqa_subjTrue_train_updated_v2_seed0_multitask.json"
val_results = "brats_gli_3d_vqa_subjTrue_val_updated_v2_seed0_multitask.json"
test_results = "brats_gli_3d_vqa_subjTrue_test_updated_v2_seed0_multitask.json"

In [3]:
with open(train_results, 'r') as f:
    train_vqa_data = json.load(f)
with open(val_results, 'r') as f:
    val_vqa_data = json.load(f)
with open(test_results, 'r') as f:
    test_vqa_data = json.load(f)

In [4]:
results1, results2, results3 = validate_vqa_lists(train_vqa_data), validate_vqa_lists(val_vqa_data), validate_vqa_lists(test_vqa_data)

Loaded 31,104 rows  (31,104)

▶ Combo distribution (overall)
          combo  n_questions
         (1, 2)         1288
      (1, 2, 3)         2013
   (1, 2, 3, 4)         1916
(1, 2, 3, 4, 5)          454
   (1, 2, 3, 5)          346
      (1, 2, 4)         2018
   (1, 2, 4, 5)          242
      (1, 2, 5)          411
         (1, 3)         1341
      (1, 3, 4)         2095
   (1, 3, 4, 5)          387
      (1, 3, 5)          461
         (1, 4)         1278
      (1, 4, 5)          429
         (1, 5)          254
           (1,)          689
         (2, 3)         1317
      (2, 3, 4)         2066
   (2, 3, 4, 5)          430
      (2, 3, 5)          503
         (2, 4)         1377
      (2, 4, 5)          347
         (2, 5)          189
           (2,)          668
         (3, 4)         1305
      (3, 4, 5)          387
         (3, 5)          204
           (3,)          667
         (4, 5)          140
           (4,)          698
           (5,)         5184

▶ Unique Q/A counts (overall)
   • questions : 30,697
   • answers   : 29,993
Loaded 4,176 rows  (4,176)

▶ Combo distribution (overall)
          combo  n_questions
         (1, 2)          326
(1, 2, 3, 4, 5)           66
   (1, 2, 3, 5)           46
      (1, 2, 4)          133
   (1, 2, 4, 5)           35
      (1, 2, 5)           55
         (1, 3)          343
   (1, 3, 4, 5)           53
      (1, 3, 5)           70
         (1, 4)          339
      (1, 4, 5)           59
         (1, 5)           34
           (1,)          150
         (2, 3)          329
   (2, 3, 4, 5)           50
      (2, 3, 5)           57
         (2, 4)          326
      (2, 4, 5)           52
         (2, 5)           28
           (2,)          165
         (3, 4)          346
      (3, 4, 5)           50
         (3, 5)           24
           (3,)          168
         (4, 5)           17
           (4,)          159
           (5,)          696

▶ Unique Q/A counts (overall)
   • questions : 4,167
   • answers   : 4,000
Loaded 3,624 rows  (3,624)

▶ Combo distribution (overall)
          combo  n_questions
         (1, 2)          306
(1, 2, 3, 4, 5)           49
   (1, 2, 3, 5)           41
   (1, 2, 4, 5)           25
      (1, 2, 5)           52
         (1, 3)          304
   (1, 3, 4, 5)           50
      (1, 3, 5)           52
         (1, 4)          307
      (1, 4, 5)           45
         (1, 5)           28
           (1,)          141
         (2, 3)          289
   (2, 3, 4, 5)           43
      (2, 3, 5)           72
         (2, 4)          310
      (2, 4, 5)           44
         (2, 5)           25
           (2,)          153
         (3, 4)          311
      (3, 4, 5)           50
         (3, 5)           19
           (3,)          142
         (4, 5)            9
           (4,)          153
           (5,)          604

▶ Unique Q/A counts (overall)
   • questions : 3,604
   • answers   : 3,482

In [5]:
for k, v in results1.items():
    display(k)
    display(v)

'combo_overall'

              combo  n_questions
10           (1, 2)         1288
4         (1, 2, 3)         2013
5      (1, 2, 3, 4)         1916
18  (1, 2, 3, 4, 5)          454
25     (1, 2, 3, 5)          346
3         (1, 2, 4)         2018
27     (1, 2, 4, 5)          242
21        (1, 2, 5)          411
7            (1, 3)         1341
1         (1, 3, 4)         2095
22     (1, 3, 4, 5)          387
17        (1, 3, 5)          461
11           (1, 4)         1278
20        (1, 4, 5)          429
26           (1, 5)          254
13             (1,)          689
8            (2, 3)         1317
2         (2, 3, 4)         2066
19     (2, 3, 4, 5)          430
16        (2, 3, 5)          503
6            (2, 4)         1377
24        (2, 4, 5)          347
29           (2, 5)          189
14             (2,)          668
9            (3, 4)         1305
23        (3, 4, 5)          387
28           (3, 5)          204
15             (3,)          667
30           (4, 5)          140
12             (4,)          698
0              (5,)         5184

'combo_per_label'

,label_name,combo,n_questions
0,Enhancing Tissue,"(1,)",157
1,Enhancing Tissue,"(1, 2)",359
2,Enhancing Tissue,"(1, 2, 3)",518
3,Enhancing Tissue,"(1, 2, 3, 4)",469
4,Enhancing Tissue,"(1, 2, 3, 4, 5)",119
...,...,...,...
119,Surrounding Non-enhancing FLAIR hyperintensity,"(3, 4, 5)",115
120,Surrounding Non-enhancing FLAIR hyperintensity,"(3, 5)",51
121,Surrounding Non-enhancing FLAIR hyperintensity,"(4,)",184
122,Surrounding Non-enhancing FLAIR hyperintensity,"(4, 5)",30
123,Surrounding Non-enhancing FLAIR hyperintensity,"(5,)",1296

'combo_per_label_type'

,label_name,type,combo,n_questions
0,Enhancing Tissue,area,"(1,)",157
1,Enhancing Tissue,area,"(1, 2)",192
2,Enhancing Tissue,area,"(1, 2, 3)",175
3,Enhancing Tissue,area,"(1, 2, 3, 4)",116
4,Enhancing Tissue,area,"(1, 2, 4)",166
...,...,...,...,...
187,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(2, 3)",181
188,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(2, 3, 4)",189
189,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3,)",151
190,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3, 4)",161
191,Surrounding Non-enhancing FLAIR hyperintensity,unknown,"(5,)",1296

'unique_q_per_label'

                                       label_name  n_unique_questions
0                                Enhancing Tissue                7669
1                             Non-Enhancing Tumor                7657
2                                Resection Cavity                7687
3  Surrounding Non-enhancing FLAIR hyperintensity                7694

'unique_a_per_label'

                                       label_name  n_unique_answers
0                                Enhancing Tissue              7542
1                             Non-Enhancing Tumor              7407
2                                Resection Cavity              7557
3  Surrounding Non-enhancing FLAIR hyperintensity              7517

'unique_q_per_label_type'

,label_name,type,n_unique_questions
0,Enhancing Tissue,area,1281
1,Enhancing Tissue,partially_unknown,1296
2,Enhancing Tissue,region,1286
3,Enhancing Tissue,satellite,1272
4,Enhancing Tissue,shape,1272
5,Enhancing Tissue,unknown,1289
6,Non-Enhancing Tumor,area,1278
7,Non-Enhancing Tumor,partially_unknown,1296
8,Non-Enhancing Tumor,region,1288
9,Non-Enhancing Tumor,satellite,1266
10,Non-Enhancing Tumor,shape,1270
11,Non-Enhancing Tumor,unknown,1292
12,Resection Cavity,area,1286
13,Resection Cavity,partially_unknown,1296
14,Resection Cavity,region,1286
15,Resection Cavity,satellite,1278
16,Resection Cavity,shape,1281
17,Resection Cavity,unknown,1290
18,Surrounding Non-enhancing FLAIR hyperintensity,area,1277
19,Surrounding Non-enhancing FLAIR hyperintensity,partially_unknown,1296
20,Surrounding Non-enhancing FLAIR hyperintensity,region,1289
21,Surrounding Non-enhancing FLAIR hyperintensity,satellite,1281
22,Surrounding Non-enhancing FLAIR hyperintensity,shape,1279
23,Surrounding Non-enhancing FLAIR hyperintensity,unknown,1295

'unique_a_per_label_type'

,label_name,type,n_unique_answers
0,Enhancing Tissue,area,1285
1,Enhancing Tissue,partially_unknown,1296
2,Enhancing Tissue,region,1279
3,Enhancing Tissue,satellite,1271
4,Enhancing Tissue,shape,1183
5,Enhancing Tissue,unknown,1241
6,Non-Enhancing Tumor,area,1273
7,Non-Enhancing Tumor,partially_unknown,1296
8,Non-Enhancing Tumor,region,1236
9,Non-Enhancing Tumor,satellite,1244
10,Non-Enhancing Tumor,shape,1183
11,Non-Enhancing Tumor,unknown,1222
12,Resection Cavity,area,1282
13,Resection Cavity,partially_unknown,1296
14,Resection Cavity,region,1283
15,Resection Cavity,satellite,1273
16,Resection Cavity,shape,1193
17,Resection Cavity,unknown,1240
18,Surrounding Non-enhancing FLAIR hyperintensity,area,1277
19,Surrounding Non-enhancing FLAIR hyperintensity,partially_unknown,1296
20,Surrounding Non-enhancing FLAIR hyperintensity,region,1286
21,Surrounding Non-enhancing FLAIR hyperintensity,satellite,1262
22,Surrounding Non-enhancing FLAIR hyperintensity,shape,1181
23,Surrounding Non-enhancing FLAIR hyperintensity,unknown,1227

In [6]:
for k, v in results2.items():
    display(k)
    display(v)

'combo_overall'

              combo  n_questions
6            (1, 2)          326
13  (1, 2, 3, 4, 5)           66
21     (1, 2, 3, 5)           46
11        (1, 2, 4)          133
22     (1, 2, 4, 5)           35
16        (1, 2, 5)           55
2            (1, 3)          343
17     (1, 3, 4, 5)           53
12        (1, 3, 5)           70
3            (1, 4)          339
14        (1, 4, 5)           59
23           (1, 5)           34
10             (1,)          150
4            (2, 3)          329
19     (2, 3, 4, 5)           50
15        (2, 3, 5)           57
5            (2, 4)          326
18        (2, 4, 5)           52
24           (2, 5)           28
8              (2,)          165
1            (3, 4)          346
20        (3, 4, 5)           50
25           (3, 5)           24
7              (3,)          168
26           (4, 5)           17
9              (4,)          159
0              (5,)          696

'combo_per_label'

,label_name,combo,n_questions
0,Enhancing Tissue,"(1,)",38
1,Enhancing Tissue,"(1, 2)",86
2,Enhancing Tissue,"(1, 2, 3, 4, 5)",20
3,Enhancing Tissue,"(1, 2, 3, 5)",15
4,Enhancing Tissue,"(1, 2, 4)",32
...,...,...,...
103,Surrounding Non-enhancing FLAIR hyperintensity,"(3, 4, 5)",12
104,Surrounding Non-enhancing FLAIR hyperintensity,"(3, 5)",8
105,Surrounding Non-enhancing FLAIR hyperintensity,"(4,)",47
106,Surrounding Non-enhancing FLAIR hyperintensity,"(4, 5)",1
107,Surrounding Non-enhancing FLAIR hyperintensity,"(5,)",174

'combo_per_label_type'

,label_name,type,combo,n_questions
0,Enhancing Tissue,area,"(1,)",38
1,Enhancing Tissue,area,"(1, 2)",41
2,Enhancing Tissue,area,"(1, 2, 4)",10
3,Enhancing Tissue,area,"(1, 3)",43
4,Enhancing Tissue,area,"(1, 4)",42
...,...,...,...,...
135,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(1, 3)",46
136,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(2, 3)",41
137,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3,)",42
138,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3, 4)",45
139,Surrounding Non-enhancing FLAIR hyperintensity,unknown,"(5,)",174

'unique_q_per_label'

                                       label_name  n_unique_questions
0                                Enhancing Tissue                1044
1                             Non-Enhancing Tumor                1039
2                                Resection Cavity                1043
3  Surrounding Non-enhancing FLAIR hyperintensity                1041

'unique_a_per_label'

                                       label_name  n_unique_answers
0                                Enhancing Tissue              1003
1                             Non-Enhancing Tumor               997
2                                Resection Cavity              1008
3  Surrounding Non-enhancing FLAIR hyperintensity              1001

'unique_q_per_label_type'

,label_name,type,n_unique_questions
0,Enhancing Tissue,area,174
1,Enhancing Tissue,partially_unknown,174
2,Enhancing Tissue,region,174
3,Enhancing Tissue,satellite,174
4,Enhancing Tissue,shape,174
5,Enhancing Tissue,unknown,174
6,Non-Enhancing Tumor,area,174
7,Non-Enhancing Tumor,partially_unknown,174
8,Non-Enhancing Tumor,region,174
9,Non-Enhancing Tumor,satellite,170
10,Non-Enhancing Tumor,shape,173
11,Non-Enhancing Tumor,unknown,174
12,Resection Cavity,area,174
13,Resection Cavity,partially_unknown,174
14,Resection Cavity,region,174
15,Resection Cavity,satellite,173
16,Resection Cavity,shape,174
17,Resection Cavity,unknown,174
18,Surrounding Non-enhancing FLAIR hyperintensity,area,174
19,Surrounding Non-enhancing FLAIR hyperintensity,partially_unknown,174
20,Surrounding Non-enhancing FLAIR hyperintensity,region,173
21,Surrounding Non-enhancing FLAIR hyperintensity,satellite,174
22,Surrounding Non-enhancing FLAIR hyperintensity,shape,172
23,Surrounding Non-enhancing FLAIR hyperintensity,unknown,174

'unique_a_per_label_type'

,label_name,type,n_unique_answers
0,Enhancing Tissue,area,172
1,Enhancing Tissue,partially_unknown,174
2,Enhancing Tissue,region,172
3,Enhancing Tissue,satellite,169
4,Enhancing Tissue,shape,152
5,Enhancing Tissue,unknown,167
6,Non-Enhancing Tumor,area,174
7,Non-Enhancing Tumor,partially_unknown,174
8,Non-Enhancing Tumor,region,171
9,Non-Enhancing Tumor,satellite,171
10,Non-Enhancing Tumor,shape,143
11,Non-Enhancing Tumor,unknown,168
12,Resection Cavity,area,174
13,Resection Cavity,partially_unknown,174
14,Resection Cavity,region,173
15,Resection Cavity,satellite,174
16,Resection Cavity,shape,149
17,Resection Cavity,unknown,166
18,Surrounding Non-enhancing FLAIR hyperintensity,area,172
19,Surrounding Non-enhancing FLAIR hyperintensity,partially_unknown,174
20,Surrounding Non-enhancing FLAIR hyperintensity,region,174
21,Surrounding Non-enhancing FLAIR hyperintensity,satellite,170
22,Surrounding Non-enhancing FLAIR hyperintensity,shape,148
23,Surrounding Non-enhancing FLAIR hyperintensity,unknown,164

In [7]:
for k, v in results3.items():
    display(k)
    display(v)

'combo_overall'

              combo  n_questions
4            (1, 2)          306
16  (1, 2, 3, 4, 5)           49
20     (1, 2, 3, 5)           41
23     (1, 2, 4, 5)           25
12        (1, 2, 5)           52
5            (1, 3)          304
15     (1, 3, 4, 5)           50
13        (1, 3, 5)           52
3            (1, 4)          307
17        (1, 4, 5)           45
21           (1, 5)           28
10             (1,)          141
6            (2, 3)          289
19     (2, 3, 4, 5)           43
11        (2, 3, 5)           72
2            (2, 4)          310
18        (2, 4, 5)           44
22           (2, 5)           25
7              (2,)          153
1            (3, 4)          311
14        (3, 4, 5)           50
24           (3, 5)           19
9              (3,)          142
25           (4, 5)            9
8              (4,)          153
0              (5,)          604

'combo_per_label'

,label_name,combo,n_questions
0,Enhancing Tissue,"(1,)",35
1,Enhancing Tissue,"(1, 2)",83
2,Enhancing Tissue,"(1, 2, 3, 4, 5)",13
3,Enhancing Tissue,"(1, 2, 3, 5)",13
4,Enhancing Tissue,"(1, 2, 4, 5)",4
...,...,...,...
99,Surrounding Non-enhancing FLAIR hyperintensity,"(3, 4, 5)",10
100,Surrounding Non-enhancing FLAIR hyperintensity,"(3, 5)",7
101,Surrounding Non-enhancing FLAIR hyperintensity,"(4,)",43
102,Surrounding Non-enhancing FLAIR hyperintensity,"(4, 5)",1
103,Surrounding Non-enhancing FLAIR hyperintensity,"(5,)",151

'combo_per_label_type'

,label_name,type,combo,n_questions
0,Enhancing Tissue,area,"(1,)",35
1,Enhancing Tissue,area,"(1, 2)",40
2,Enhancing Tissue,area,"(1, 3)",42
3,Enhancing Tissue,area,"(1, 4)",34
4,Enhancing Tissue,partially_unknown,"(1, 2, 3, 4, 5)",13
...,...,...,...,...
123,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(1, 3)",41
124,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(2, 3)",34
125,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3,)",38
126,Surrounding Non-enhancing FLAIR hyperintensity,shape,"(3, 4)",38
127,Surrounding Non-enhancing FLAIR hyperintensity,unknown,"(5,)",151

'unique_q_per_label'

                                       label_name  n_unique_questions
0                                Enhancing Tissue                 895
1                             Non-Enhancing Tumor                 900
2                                Resection Cavity                 905
3  Surrounding Non-enhancing FLAIR hyperintensity                 904

'unique_a_per_label'

                                       label_name  n_unique_answers
0                                Enhancing Tissue               875
1                             Non-Enhancing Tumor               865
2                                Resection Cavity               872
3  Surrounding Non-enhancing FLAIR hyperintensity               876

'unique_q_per_label_type'

,label_name,type,n_unique_questions
0,Enhancing Tissue,area,146
1,Enhancing Tissue,partially_unknown,151
2,Enhancing Tissue,region,148
3,Enhancing Tissue,satellite,149
4,Enhancing Tissue,shape,150
5,Enhancing Tissue,unknown,151
6,Non-Enhancing Tumor,area,149
7,Non-Enhancing Tumor,partially_unknown,151
8,Non-Enhancing Tumor,region,150
9,Non-Enhancing Tumor,satellite,151
10,Non-Enhancing Tumor,shape,148
11,Non-Enhancing Tumor,unknown,151
12,Resection Cavity,area,151
13,Resection Cavity,partially_unknown,151
14,Resection Cavity,region,151
15,Resection Cavity,satellite,151
16,Resection Cavity,shape,150
17,Resection Cavity,unknown,151
18,Surrounding Non-enhancing FLAIR hyperintensity,area,151
19,Surrounding Non-enhancing FLAIR hyperintensity,partially_unknown,151
20,Surrounding Non-enhancing FLAIR hyperintensity,region,151
21,Surrounding Non-enhancing FLAIR hyperintensity,satellite,150
22,Surrounding Non-enhancing FLAIR hyperintensity,shape,150
23,Surrounding Non-enhancing FLAIR hyperintensity,unknown,151

'unique_a_per_label_type'

,label_name,type,n_unique_answers
0,Enhancing Tissue,area,151
1,Enhancing Tissue,partially_unknown,151
2,Enhancing Tissue,region,149
3,Enhancing Tissue,satellite,147
4,Enhancing Tissue,shape,131
5,Enhancing Tissue,unknown,149
6,Non-Enhancing Tumor,area,151
7,Non-Enhancing Tumor,partially_unknown,151
8,Non-Enhancing Tumor,region,147
9,Non-Enhancing Tumor,satellite,145
10,Non-Enhancing Tumor,shape,127
11,Non-Enhancing Tumor,unknown,147
12,Resection Cavity,area,151
13,Resection Cavity,partially_unknown,151
14,Resection Cavity,region,148
15,Resection Cavity,satellite,150
16,Resection Cavity,shape,130
17,Resection Cavity,unknown,145
18,Surrounding Non-enhancing FLAIR hyperintensity,area,151
19,Surrounding Non-enhancing FLAIR hyperintensity,partially_unknown,151
20,Surrounding Non-enhancing FLAIR hyperintensity,region,151
21,Surrounding Non-enhancing FLAIR hyperintensity,satellite,150
22,Surrounding Non-enhancing FLAIR hyperintensity,shape,125
23,Surrounding Non-enhancing FLAIR hyperintensity,unknown,149